version: '3.8'
services:

  todolist-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ToDoList
      MYSQL_USER: todoappuser
      MYSQL_PASSWORD: secretpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - db-network

  aspnet-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - todolist-db
    environment:
      - ConnectionStrings__DefaultConnection=server=todolist-db;port=3306;database=ToDoList;user=root;password=rootpassword
      - ASPNETCORE_URLS=http://0.0.0.0:5131
    networks:
      - db-network
      - todo-network

  prometheus:
    image: prom/prometheus:v3
    volumes:
      - ./prometheus:/etc/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - todo-network

  node-exporter:
    image: prom/node-exporter:master-distroless
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - todo-network

  grafana:
    image: grafana/grafana:13.1.0-25027462778
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    networks:
      - todo-network

  nginx:
    image: nginx:stable-alpine3.23-perl
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - aspnet-server
    networks:
      - todo-network
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"


networks:
  todo-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  db-network:
    internal: true

volumes:
  mysql-data:
  grafana_data:
